apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  namespace: jachimike
spec:
  type: NodePort
  selector:
    app: result-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31002
