apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
  namespace: jachimike
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      labels:
        app: voting-app
    spec:
      containers:
      - name: voting-app
        image: bludive/votingapp
        ports:
        - containerPort: 80

