apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
  namespace: jachimike
  annotations:
    version: "1.16"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nginx:1.16
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret

