apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: jachimike
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 31000

